version: '3.2'
services:
  streaming-service:
    build: ./streaming-service
    environment:
      VIDEO_DIR: ./videos
      KAFKA_BROKER: "broker:29092"
    ports:
      - "3001:3001"
    volumes:
      - "./streaming-service/videos:/usr/app/videos"
    depends_on:
      - broker
    networks:
        default:
            aliases:  
                - streaming-service
    
  video-data-service:
    build: ./video-data-service
    environment:
      VIDEO_DIR: ./videos
      KAFKA_BROKER: "broker:29092"
      DATABASE_URL: "postgresql://admin:admin@postgres-db:5432/video-data?schema=public"
    ports:
      - "3000:3000"
    depends_on:
      - broker
      - db
    networks:
        default:
            aliases:  
                - video-data-service

  zookeeper:
    extends:  
      file: ./kafka-docker-compose/docker-compose.yml
      service: zookeeper

  broker:
    extends:
      file: ./kafka-docker-compose/docker-compose.yml
      service: broker

  kafka-ui:
    extends:
      file: ./kafka-docker-compose/docker-compose.yml
      service: kafka-ui
  
  kafka-init-topics:
    extends:
      file: ./kafka-docker-compose/docker-compose.yml
      service: kafka-init-topics

  db:
    extends:
      file: ./dev-db/docker-compose.yml
      service: postgres

networks:
  default:
    driver: bridge