version: '3.2'
services:
  streaming-service:
    build: ./streaming-service
    environment:
      VIDEO_DIR: ./videos
      KAFKA_BROKER: "broker:29092"
    ports:
      - "3000:3000"
    volumes:
      - "./streaming-service/videos:/usr/app/videos"
    depends_on:
      - broker
    networks:
        default:
            aliases:  
                - streaming-service

  zookeeper:
    extends:  
      file: ./kafka-docker-compose/docker-compose.yml
      service: zookeeper

  broker:
    extends:
      file: ./kafka-docker-compose/docker-compose.yml
      service: broker

  kafka-ui:
    extends:
      file: ./kafka-docker-compose/docker-compose.yml
      service: kafka-ui
  
  kafka-init-topics:
    extends:
      file: ./kafka-docker-compose/docker-compose.yml
      service: kafka-init-topics

networks:
  default:
    driver: bridge