version: '3.8'
services:
  postgres:
    image: postgres:latest
    container_name: postgres-db
    environment:
      POSTGRES_DB: video-data
      POSTGRES_USER: yourusername
      POSTGRES_PASSWORD: yourpassword
    volumes:
      - ./db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
